const {chromium}=require('playwright');
const fs=require('fs');
const assert=require('node:assert/strict');
(async()=>{
const browser=await chromium.launch({executablePath:process.env.PWA_CHROMIUM_PATH || undefined,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844},serviceWorkers:'block',isMobile:true,hasTouch:true});
const now=new Date().toISOString();
const user={id:'u1',name:'Agente Demo',email:'demo@example.test',role:'AGENT',organizationId:'o1',mustChangePassword:false,organization:{id:'o1',name:'Equipo Demo',slug:'demo'}};
const contact={id:'ct1',name:'María González',phone:'595981555111',email:null,tags:[],crmTags:[]};
const conv={id:'c1',subject:null,status:'OPEN',priority:'NORMAL',channel:'whatsapp',tags:[],createdAt:now,updatedAt:now,contact,department:null,assignedTo:user,unreadCount:1,lastMessage:{content:'Hola, ¿me ayudan con mi pedido?',direction:'INBOUND',contentType:'text',at:now}};
const msg={id:'m1',conversationId:'c1',direction:'INBOUND',content:'Hola, ¿me ayudan con mi pedido?',contentType:'text',deliveryStatus:'delivered',waMessageId:null,quotedMessageId:null,reactions:[],createdAt:now,sender:null,attachment:null,transcription:null};
const errors=[],requests=[];
await context.route('**/socket.io/**',r=>r.fulfill({status:200,body:'0{"sid":"fixture","upgrades":[],"pingInterval":100000,"pingTimeout":20000}'}));
await context.route('**/api/**',async r=>{
 const req=r.request(),p=new URL(req.url()).pathname; requests.push({p,method:req.method(),body:req.postData()});
 let data={};
 if(p==='/api/auth/me') data={user};
 else if(p==='/api/org/whatsapp/status')data={status:'connected'};
 else if(p==='/api/org/conversations')data={conversations:[conv,{...conv,id:'c2',contact:{...contact,id:'ct2',name:'Carlos López'}}]};
 else if(p==='/api/org/conversations/unread-summary')data={conversations:1};
 else if(p==='/api/org/conversations/c1'||p==='/api/org/conversations/c2')data={conversation:conv,messages:[msg]};
 else if(p.endsWith('/messages')&&req.method()==='POST')data={message:{...msg,id:'m2',direction:'OUTBOUND',content:JSON.parse(req.postData()).content}};
 else if(p.endsWith('/messages')) data={messages:[]};
 else if(p.endsWith('/transfer'))data={conversation:conv};
 else if(p==='/api/org/orders')data={orders:[]};
 else if(p==='/api/org/contacts/directory')data={contacts:[{...contact,avatarUrl:null,createdAt:now,conversationId:'c1',crmStage:'Abiertas'}],total:1,page:1,pages:1,tags:[],stats:{total:1,withName:1,withPhone:1}};
 else if(p==='/api/org/reports/summary')data={period:{days:30},conversations:{total:2,byStatus:{OPEN:2},byChannel:[],byDepartment:[],byAgent:[],resolutionRate:0,avgFirstResponseMinutes:1},orders:{total:0,byStatus:{},revenue:0}};
 else if(p==='/api/org/dashboard-stats')data={kpis:{messages:{total:2,today:2,inbound:1,outbound:1,notes:0,bot:0,responseRate:100,avgFirstResponseMinutes:1},conversations:{total:2,open:2},orders:{total:0,revenueTotal:0},agents:{total:1,onlineCount:1,list:[]},bot:{active:false}},recentUnassigned:[],dailyActivity:[]};
 else if(p==='/api/org/users')data={users:[{...user,id:'u2',name:'Lucía Soporte',active:true}]};
 else if(p==='/api/org/departments')data={departments:[{id:'d1',name:'Soporte',members:[]}]};
 else if(p==='/api/org/presence')data={presence:[]};
 else if(p==='/api/org')data={organization:{settings:{}}};
 else if(p==='/api/org/billing/status')data={access:{state:'active',blocked:false,msLeft:999999999},payments:[]};
 else if(p.endsWith('/notices'))data={notices:[]};
 else if(p.includes('quick-replies'))data={quickReplies:[],replies:[],items:[]};
 else if(p.includes('push/vapid'))data={configured:false};
 else if(p.includes('statuses'))data={statuses:[],contacts:[],groups:[]};
 else if(p.includes('notifications'))data={notifications:[],unreadCount:0};
 await r.fulfill({json:data});
});
const page=await context.newPage();page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR',e.message,e.stack)});
await page.goto('http://127.0.0.1:5189/inbox');
await page.getByText('María González',{exact:true}).first().waitFor();
await page.screenshot({path:'/tmp/niro-mobile-list.png'});
assert.equal(await page.locator('.crm-chat-column').isVisible(),false);
await page.getByText('María González',{exact:true}).first().click();
await page.locator('.crm-chat-textarea').fill('Borrador para María');
await page.getByRole('button',{name:'Chats',exact:true}).click();
await page.getByText('Carlos López',{exact:true}).first().click();
assert.equal(await page.locator('.crm-chat-textarea').inputValue(),'');
await page.getByRole('button',{name:'Chats',exact:true}).click();
await page.getByText('María González',{exact:true}).first().click();
assert.equal(await page.locator('.crm-chat-textarea').inputValue(),'Borrador para María');
await context.setOffline(true);
const beforeOffline = requests.filter(r=>r.p.endsWith('/messages') && r.method==='POST').length;
await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();
assert.equal(await page.locator('.crm-chat-textarea').inputValue(),'Borrador para María');
assert.equal(requests.filter(r=>r.p.endsWith('/messages') && r.method==='POST').length,beforeOffline);
await context.setOffline(false);
await page.getByRole('button',{name:'Enviar mensaje',exact:true}).click();
await page.waitForFunction(()=>document.querySelector('.crm-chat-textarea').value==='');
assert(requests.some(r=>r.p.endsWith('/messages')&&r.body?.includes('Borrador para María')));
await page.screenshot({path:'/tmp/niro-mobile-chat.png'});
const geometry=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,composer:document.querySelector('.crm-chat-composer').getBoundingClientRect().bottom,height:innerHeight}));
assert(geometry.scroll<=geometry.width,JSON.stringify(geometry)); assert(geometry.composer<=geometry.height+1,JSON.stringify(geometry));
await page.setViewportSize({width:390,height:430});
await page.locator('.crm-chat-textarea').focus();
await page.waitForTimeout(100);
assert((await page.locator('.crm-chat-messages-body').boundingBox()).height > 100);
await page.locator('.crm-chat-textarea').blur();
await page.setViewportSize({width:390,height:844});
await page.getByRole('button',{name:'Contacto',exact:true}).click();
assert(await page.locator('.crm-info-column').isVisible());
await page.locator('.crm-info-close-btn').click();
await page.getByTitle('Transferir chat a otro agente',{exact:true}).click();
await page.getByRole('button',{name:/Lucía Soporte/}).click();
await page.screenshot({path:'/tmp/niro-mobile-transfer.png'});
await page.getByRole('button',{name:/Confirmar Transferencia/}).click();
assert(requests.some(r=>r.p.endsWith('/transfer')&&r.body?.includes('u2')));
await page.getByRole('button',{name:'Abrir menú',exact:true}).click();
assert(await page.locator('.modern-sidebar').isVisible());
await page.screenshot({path:'/tmp/niro-mobile-menu.png'});
await page.getByRole('button',{name:'Cerrar menú',exact:true}).first().click({position:{x:380,y:100}}).catch(()=>page.keyboard.press('Escape'));
const widths=[];
for(const width of [320,360,390,768,1024,1440]){
 await page.setViewportSize({width,height:900});
 const g=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,composer:document.querySelector('.crm-chat-composer').getBoundingClientRect().bottom,height:innerHeight}));
 assert(g.scroll<=g.width,JSON.stringify(g));assert(g.composer<=g.height+1,JSON.stringify(g)); widths.push(g);
}
await page.screenshot({path:'/tmp/niro-desktop-chat.png'});
const modules=[];
await page.setViewportSize({width:390,height:844});
for(const [route,selector] of [['/dashboard','.modern-main-area'],['/contactos','.contacts-toolbar'],['/orders','.page-header'],['/reports','.reports-page'],['/board','.crm-board-wrap']]) {
 await page.goto('http://127.0.0.1:5189'+route);
 await page.locator(selector).waitFor();
 await page.waitForTimeout(150);
 const g=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));
 assert(g.scroll<=g.width,route+JSON.stringify(g));
 assert((await page.locator('main').innerText()).trim().length>30);
 await page.screenshot({path:'/tmp/niro-module-'+route.slice(1)+'.png'});
 modules.push(route);
}
console.log(JSON.stringify({errors,widths,geometry,modules,mutations:requests.filter(r=>r.method==='POST').map(r=>r.p)},null,2));
assert.equal(errors.length,0);
await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
